### ISSUE TITLE
Delve licensing question

### ISSUE THREAD

**Issue by Anth0rx** [rsek/datasworn#17]
On the [official website](https://www.ironswornrpg.com/product-ironsworn-delve) an Ironsworn: Delve **free preview** can be downloaded which contains only the first two chapters and is licensed under a CC-BY-NC-SA 4.0 International license.

The full version is a paid commercial product. That is probably why this repository contains Ironsworn: Delve specific content only from the first two chapters, correct?

**Comment by rsek** [comment]
the text of delve is actually CC-BY-NC-SA 4.0 too! here's a screencap of the credits page at the front of the book:
<img width="411" alt="Screen Shot 2022-10-04 at 8 47 17 AM" src="https://user-images.githubusercontent.com/5354757/193865466-95a7e81b-6161-42c0-8045-e28ce36e2d1d.png">

there's content from other chapters (e.g. oracles, moves, encounters/foes) scattered through the various files, but they're especially well-organized about it.

i've been working on a more complete + more detailed version of the data for Datasworn, that's mostly compatible with [Dataforged](https://github.com/rsek/dataforged).

if you're using Node for your project, it's available in [the package on NPM](https://www.npmjs.com/package/dataforged) by importing the `ironsworn` object. it also benefits from the Typescript typings.

if you're not using Node, the `dist` folder of the release package contains the full JSON and their JSON schemas in the `dist/ironsworn` directory: https://github.com/rsek/dataforged/releases/tag/v1.5.0

**however**, there's a couple caveats on that:

* the ironsworn-specific data there is a preview, e.g. not totally stable. case in point... well, see the next item
* there's extensive breaking changes in dataforged 2.0/datasworn 2.0 (both of which i'd like to release some time this month). so if you only want to migrate once, you might want to defer doing so

**Comment by Anth0rx** [comment]
Thanks for your prompt response. That is interesting. Thank you so much for your great work on Dataforged.
Is there a place where I get the PDF version of Ironsworn: Delve? Why do they have a paid option for the PDF on their site when the document is CC-BY-NC-SA 4.0?

**Comment by rsek** [comment]
to my knowledge, there's nothing really stopping anyone from putting the text (and only the text) online and redistributing it under CC-BY-NC-SA. that would probably require fair amount of processing, hand-editing, or both.

something like a [System Reference Document](https://en.wikipedia.org/wiki/System_Reference_Document), on the other hand, usually only makes sense to do with a license that allows for commercial work, like the OGL or CC-BY. SRDs aren't really intended as a player reference in the first place -- they're for designers wanting to build their game on the same rules skeleton.

as to why, shawn would probably know that better than i do. you could always ask him on the discord if you want :)

**Comment by Anth0rx** [comment]
Thanks for elaborating on this. I didn't get the detail, that **only the text** is CC-BY-NC-SA 4.0. Then it makes perfect sense the way Shawn distributes the PDF.

The Ironsworn SRD contains only the core rules without the Delve supplement, correct?
