### ISSUE TITLE
Text Formatting Differs between Moves and Assets for referencing a move.

### ISSUE THREAD

**Issue by HAJ523** [rsek/datasworn#2]
In the Assets.json moves are referenced by making them Italic: `*Move*`
In the Moves.json other moves are referenced by making them underlined: `_Move_`

Consistency will help readers.
If the markdown for moves was unique and consistent then programmers could use it for things like making those moves into clickable links to actually perform the move.

**Comment by rsek** [comment]
simple enough. fixed in #747a45ad2abb814b15e3035e2c4aa9535bf57331
